### ISSUE TITLE
Automatic firewall addition start failing in Azure SSAS deployment

### ISSUE THREAD

**Issue by leelaperipydi** [liprec/vsts-release-aas#115] opened 2022-10-19 02:14 UTC
*Start issue here*

Getting below error while deploying to Azure SSAS using ADO pipeline. This started only this weekend, till Friday (10/14/2022) afternoon 2 PM CST/CDT it worked well. Monday morning it started failing. Not sure what changed. 

Please guide me any issue with invoke-restmethod for adding firewall?  

**##[error]The IP firewall settings is invalid because the IP address <ip>xxx.xxx.xxx.xxx</ip> can't be parsed. Please make sure the IP address is in the standard IP v4 notation.**

Thanks,
Leela

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=a3e3c8b6-d785-4bd4-a648-cd6d472775bb
* document_url=https://azurebi-docs.jppp.org/vsts-extensions/index.html

**Comment by liprec** [comment] 2022-10-19 06:03
Closed due to a duplicate of #113

**Closed by liprec** 2022-10-19 06:03 UTC

**Comment by leelaperipydi** [comment] 2022-10-19 14:29
Thank you for quick action. It started working now.
