### ISSUE TITLE
Admin Login for Analysis services

### ISSUE THREAD

**Issue by niya90** [liprec/vsts-release-aas#9] opened 2018-04-05 10:54 UTC
Hi Team,

On VSTS , I wanted to use SPN to connect to analysis services on Production environment, But when I am trying to pass variables with SPN username and Password, it is not logging in to analysis services, it give error exception has been thrown by target of invocation.
Can you please guide me on User credentials I need to give.

**Comment by liprec** [comment] 2018-04-12 19:34
I am considering this a duplicate of #5 and am closing it therefor.

**Closed by liprec** 2018-04-12 19:34 UTC
Labels: bug, duplicate
