### ISSUE TITLE
Deployment Task unable to update Firewall rules and failing with below error

### ISSUE THREAD

**Issue by rajesh-g84** [liprec/vsts-release-aas#114] opened 2022-10-18 20:58 UTC
The IP firewall settings is invalid because the IP address <ip>*******</ip> can't be parsed. Please make sure the IP address is in the standard IP v4 notation.

We are deploying to Azure Analysis Services using Named User Login Type. The task was working fine till 10/14, but not working anymore

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=4381b0c0-3a30-42ba-ad70-47e99b1994e1
* document_url=https://azurebi-docs.jppp.org/vsts-extensions/azure-analysis-service-deploy.html

**Comment by liprec** [comment] 2022-10-19 06:03
Closed due to a duplicate of #113

**Closed by liprec** 2022-10-19 06:03 UTC
